### ISSUE TITLE
Video block not working

### ISSUE THREAD

**Issue by Alejandro-Reapertips** [mchlkucera/notion-to-html#5]
Hello! – I noticed that when inserting a video block on Notion, then running the make automation, this is the output of the video:

`<figure style="padding-bottom:56.206088992974244%" class="w-richtext-align-fullwidth w-richtext-figure-type-video"><iframe src="https://www.youtube.com/embed/ttps://youtu.be/GjtEIYXrqa8?feature=oembed" frameBorder="0" sandbox="allow-scripts allow-popups allow-top-navigation-by-user-activation allow-forms allow-same-origin"></iframe><figcaption>ㅤ</figcaption>`

I believe it has to do with this part not being properly formatted: `"https://www.youtube.com/embed/ttps://youtu.be/GjtEIYXrqa8?feature=oembed"`

I also tried inserting a Vimeo embed and the output was like this: 
`<figure style="padding-bottom:56.206088992974244%" class="w-richtext-align-fullwidth w-richtext-figure-type-video"><iframe src="https://www.youtube.com/embed/ttps://vimeo.com/769635358?feature=oembed" frameBorder="0" sandbox="allow-scripts allow-popups allow-top-navigation-by-user-activation allow-forms allow-same-origin"></iframe><figcaption>ㅤ</figcaption></figure>`

So I think to fix this, you have to filter out `ttps://youtu.be/` so it becomes `"https://www.youtube.com/embed/GjtEIYXrqa8?feature=oembed"`

I am guessing Vimeo won't work, though? I was hoping I could use it but it's okay if just youtube can work. 

Thank you so much for your help <3

**Comment by mchlkucera** [comment]
Fixed the dysfunctional Youtube links and added support for Vimeo videos. Please give it a test

**Comment by mchlkucera** [comment]
Thanks so much for the contribution!

**Comment by Alejandro-Reapertips** [comment]
Works beautifully, Michal! – What a relief :) – just tested both Vimeo and Youtube. I owe you so much! 🥰
