### ISSUE TITLE
Inline-code formatting has some extra padding on the left side when it's inside a numbered lists 

### ISSUE THREAD

**Issue by alez156** [mchlkucera/notion-to-html#8]
I noticed that when using inline-code formatting and it's located inside a numbered list, it will add some extra padding on the left side to the inline code. It looks like this:
![image](https://user-images.githubusercontent.com/21991578/202802199-c507178f-31db-423f-9a3c-ec7b35c14a26.png)
You can see it live here: https://reapertips.webflow.io/post/how-to-install-reapack

This padding doesn't occur when it's not in numbered/bullet list as you can see here:
![image](https://user-images.githubusercontent.com/21991578/202802471-4a8db5e0-39c5-4563-823f-86631f6b39bc.png)

This is not big priority, it just looks a bit weird~ 

Thank you!

**Comment by mchlkucera** [comment]
Please tweak your `.inline-block` class.
Remove the `display: inline-block`, remove the `padding` and add `padding: 0.1rem 0.2rem`.
When the element has a display of inline-block it behaves unexpectedly (as a list child element).

![image](https://user-images.githubusercontent.com/70275735/202898502-70fe2604-69dc-4473-ba50-c7fd2e2e8516.png)
![image](https://user-images.githubusercontent.com/70275735/202898549-22bddf20-7371-47b3-8830-25fab31157d7.png)

Don't forget to close the issue if this solves your problem:-)

**Comment by alez156** [comment]
Beautiful! 💙 works great! Thank you.
